<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'weider');
define('_DB_USER_', 'weider');
define('_DB_PASSWD_', 's25m77');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', '2tknPL1xLOkQ2FCiq9Ie98Z2DY7DPe6atvHazdsKBRfF8PvayMhYqyHH');
define('_COOKIE_IV_', 'DPKiIXfu');
define('_PS_CREATION_DATE_', '2014-06-18');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.7');
define('_RIJNDAEL_KEY_', 'ZXS8W9CIZ5M6hi7KTsMF9Dy1d73rkDdh');
define('_RIJNDAEL_IV_', 'JPXmYHZFbVp48odxBHpH7A==');
